[storage,refactor][xs]: remove slightly weird method caching of ofs impl object on 'storage' package, relocating it to ofs property on controller where it is used.
* Main motivation was to avoid errors on startup (e.g. use of paster serve in development mode) of form::
  return GSConnection(gs_access_key_id, gs_secret_access_key, **kwargs)
  TypeError: __init__() got an unexpected keyword argument 'gs_bucket'
* (May still be a problem in the storage extension but at least we can start ckan!)